### ISSUE TITLE
Missing frames in the kinetics14 dataset

### ISSUE THREAD

**Issue by wlin-at** [vturrisi/CO2A#3]
Hi, thanks for sharing the nice work and dataset!

I notice that in the kinetics14 dataset, quite some videos only have less than 5 frames, where one cannot tell what the action is in such few frames. However, I assume the original videos are a lot longer.
For example, 
`kinetics14/train/backflip/0bz6tFnaWB8_000000_000010`, `kinetics14/train/backflip/410EkXlnxVY_000000_000010` have 1 frame
`kinetics14/train/backflip/0nrsxZWhfZs_000000_000010`, `kinetics14/train/backflip/462rS0uSATs_000000_000010` have 2 frames
`kinetics14/train/backflip/_1W44j2lpIA_000000_000010`, `/media/data_8T/Mixamo_Kinetics/kinetics14/train/backflip/0cjYqFiKr7o_000000_000010`, `/media/data_8T/Mixamo_Kinetics/kinetics14/train/backflip/4AuDEB6_duk_000000_000010` have 3 frames

As there are quite a lot of videos in these cases of missing frames, I wonder if this is the frame extraction / data storage issue. If so, could you also upload the corrected version with complete video frames? 

Thanks a lot for the efforts!

Best,

Wei

**Comment by gzaraunitn** [comment]
Hi, thank you for notifying this! 

Unfortunately when it comes to the Kinetics datasets this may occur often: since the dataset page only provides Youtube links, for the download of the video sequences we need to rely on some downloading tool that possibly works with the current policy of Youtube (they change very often), or at least this was the case when we downloaded the data. Still, such tools may sometimes fail on some videos or single frames for various reasons. This is why, as you may have noticed, at data-loading time we only load videos that have enough frames and discard the others.

We are a bit busy at the moment, but we plan to upload in the near future a new version of the datasets divided in chunks in order to make the download easier: we will remove from this version the videos that do not have enough frames! Anyway, should you be interested, the Youtube ID of the videos is included in the path of our dataset, e.g., 
`kinetics14/train/backflip/0bz6tFnaWB8_000000_000010` is downloaded from the youtube video with ID `0bz6tFnaWB8`. 

Best,
Giacomo
